# Generated by Django 5.0.3 on 2025-11-25 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_supplier_follow_supplier_and_more'),
        ('returnrequest', '0013_balancewithdrawrequest_risk_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_returns', to='accounts.delivery'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAWAL_REQUEST', 'Withdrawal Request'), ('WITHDRAWAL_COMPLETED', 'Withdrawal Completed'), ('WITHDRAWAL_CANCELLED', 'Withdrawal Cancelled'), ('RETURN_CREDIT', 'Return Credit'), ('RETURN_DEBIT', 'Return Debit'), ('CASH_BACK', 'Cash Back'), ('RETURNED_CASH_BACK', 'Returned Cash Back'), ('RETURNED_PRODUCT', 'Returned Product'), ('PURCHASED_PRODUCTS', 'Purchased Products'), ('DELIVERY_FEE', 'Delivery Fee'), ('SUPPLIER_TRANSFER', 'Supplier Transfer'), ('REFUND_FAILED', 'Refund Failed'), ('PURCHASED_COURSE', 'Purchased Course')], max_length=50),
        ),
    ]
