# Generated by Django 5.2.14 on 2026-05-28 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_options'),
        ('returnrequest', '0014_returnrequest_delivery_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Standard Return Policy', max_length=255, verbose_name='Title')),
                ('max_days_for_return', models.PositiveIntegerField(default=14, verbose_name='Max Days For Return')),
                ('allowed_conditions', models.JSONField(default=list, verbose_name='Allowed Conditions')),
                ('requires_admin_approval', models.BooleanField(default=False, verbose_name='Requires Admin Approval')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_policy', to='accounts.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Return Policy',
                'verbose_name_plural': 'Return Policies',
            },
        ),
    ]
