server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    # Caching for static assets
    location ~* \.(?:css|js|jpg|jpeg|svg|png|woff2|woff|ttf|ico|gif)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Route /dashboard traffic to the dashboard SPA
    location /dashboard {
        alias /usr/share/nginx/html/dashboard;
        index index.html app.html;
        try_files $uri $uri/ /dashboard/index.html /dashboard/app.html;
    }

    # Route /sysadmin traffic to the sysadmin SPA
    location /sysadmin {
        alias /usr/share/nginx/html/sysadmin_dashboard;
        index index.html app.html;
        try_files $uri $uri/ /sysadmin/index.html /sysadmin/app.html;
    }
}
