# Generated by Django 5.1.15 on 2026-06-25 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('script_content', models.TextField()),
                ('interpreter', models.CharField(default='/bin/bash', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('os_type', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=100)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('resource', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SELinuxContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('expected_context', models.CharField(max_length=255)),
                ('current_context', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('match', 'Match'), ('mismatch', 'Mismatch')], default='match', max_length=50)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selinux_contexts', to='system_admin.server')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to='system_admin.server')),
            ],
        ),
        migrations.CreateModel(
            name='LogicalVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vg_name', models.CharField(max_length=100)),
                ('lv_name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=50)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logical_volumes', to='system_admin.server')),
            ],
        ),
        migrations.CreateModel(
            name='LinuxUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('sudo_access', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linux_users', to='system_admin.server')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_admin.server')),
            ],
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=20)),
                ('protocol', models.CharField(default='tcp', max_length=20)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_rules', to='system_admin.server')),
            ],
        ),
        migrations.CreateModel(
            name='DiskVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount_point', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('used', models.CharField(max_length=50)),
                ('available', models.CharField(max_length=50)),
                ('health', models.CharField(default='healthy', max_length=50)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_volumes', to='system_admin.server')),
            ],
        ),
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('command', models.TextField()),
                ('user', models.CharField(default='root', max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_jobs', to='system_admin.server')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('ports', models.CharField(blank=True, max_length=255, null=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='system_admin.server')),
            ],
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('backup_type', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=50)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_jobs', to='system_admin.server')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='stopped', max_length=50)),
                ('last_restart', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='system_admin.server')),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to='system_admin.server')),
            ],
        ),
    ]
