# Generated by Django 4.2.30 on 2026-06-06 19:24

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('PhoneNO', models.CharField(max_length=14, verbose_name='Phone number')),
                ('Balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('is_delivery', models.BooleanField(default=False)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='FCM Token')),
                ('last_password_reset_request', models.DateTimeField(blank=True, null=True)),
                ('auth_provider', models.CharField(default='email', max_length=50)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('can_approve_withdrawals', 'Can approve withdrawals'), ('can_refund_orders', 'Can refund orders'), ('can_suspend_users', 'Can suspend users'), ('can_verify_suppliers', 'Can verify suppliers'), ('can_manage_courses', 'Can manage courses'), ('can_manage_products', 'Can manage products'), ('can_manage_disputes', 'Can manage disputes'), ('can_view_financial_reports', 'Can view financial reports'), ('can_view_audit_logs', 'Can view audit logs'), ('can_manage_support_tickets', 'Can manage support tickets'), ('can_moderate_reviews', 'Can moderate reviews')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierPhoto', models.ImageField(blank=True, null=True, upload_to='supplier_photos/%y/%m/%d')),
                ('SupplierCover', models.ImageField(blank=True, null=True, upload_to='supplier_covers/%y/%m/%d')),
                ('CategoryTitle', models.CharField(max_length=50)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='supplier_logos/%y/%m/%d')),
                ('SupplierContract', models.FileField(upload_to='supplier_contracts/%y/%m/%d')),
                ('SupplierIdentity', models.FileField(upload_to='supplier_identities/%y/%m/%d')),
                ('FollowersNo', models.PositiveIntegerField(default=0)),
                ('ExperienceYears', models.IntegerField(blank=True, null=True)),
                ('Rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('Orders', models.IntegerField(blank=True, null=True)),
                ('accepted_supplier', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{13,16}$', 'Enter a valid card number (13-16 digits).')])),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('other', 'Other')], default='visa', max_length=20)),
                ('expiry_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expiry_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2099)])),
                ('cvv', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{3,4}$', 'Enter a valid CVV (3 or 4 digits).')])),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Card',
                'verbose_name_plural': 'Payment Cards',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryPhoto', models.ImageField(upload_to='shipper_photos/%y/%m/%d')),
                ('DeliveryContract', models.ImageField(upload_to='shipper_contracts/%y/%m/%d')),
                ('DeliveryIdentity', models.ImageField(upload_to='shipper_identities/%y/%m/%d')),
                ('VehicleModel', models.CharField(max_length=100)),
                ('VehicleColor', models.CharField(blank=True, max_length=100, null=True)),
                ('plateNO', models.CharField(max_length=100)),
                ('Rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('Orders', models.IntegerField(blank=True, null=True)),
                ('ExperienceYears', models.IntegerField(blank=True, null=True)),
                ('governorate', models.CharField(default='default_governorate', max_length=100)),
                ('accepted_delivery', models.BooleanField(default=False)),
                ('performance_tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerPhoto', models.ImageField(blank=True, null=True, upload_to='customer_photos/%y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildingNO', models.CharField(max_length=10, null=True)),
                ('Street', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_signature', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'device_signature')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_object_id', models.PositiveIntegerField(default=0)),
                ('follower_content_type', models.ForeignKey(default=accounts.models.get_default_customer_content_type, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier')),
            ],
            options={
                'indexes': [models.Index(fields=['follower_content_type', 'follower_object_id'], name='follow_follower_idx'), models.Index(fields=['supplier'], name='follow_supplier_idx')],
                'unique_together': {('follower_content_type', 'follower_object_id', 'supplier')},
            },
        ),
    ]
