# Generated by Django 5.1.15

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_role',
            field=models.CharField(blank=True, choices=[('sysadmin', 'System Administrator'), ('support', 'Customer Support'), ('operations', 'Operations Staff'), ('developer', 'Platform Developer'), ('db_admin', 'Database Administrator'), ('test', 'Test Automation')], max_length=20, null=True, verbose_name='Team Role'),
        ),
    ]
