# Generated by Django on the date you are running this.
# For example: # Generated by Django 5.0.3 on 2024-06-26 02:58

import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    PaymentHistory = apps.get_model("payment", "PaymentHistory")
    for row in PaymentHistory.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymenthistory_stripe_payment_intent_id'),
    ]

    operations = [
        # Simply replace the old PK with a new UUID PK
        # This bypasses SQLite's limitations with renaming primary key columns
        migrations.RemoveField(
            model_name='paymenthistory',
            name='id',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        # Add the new fields from your original migration
        migrations.AddField(
            model_name='paymenthistory',
            name='address_id',
            field=models.UUIDField(blank=True, help_text='The address used for the order.', null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='cart',
            field=models.ForeignKey(blank=True, help_text='The associated cart for the payment.', null=True, on_delete=models.SET_NULL, to='orders.cart'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='The coupon code used for the order.', max_length=50, null=True),
        ),
    ]