# Generated by Django 5.0.3 on 2026-05-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_shipment_created_at'),
        ('products', '0014_collectionitem_unique_collection_item'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(fields=('wishlist', 'product'), name='unique_wishlist_item'),
        ),
    ]
