# Generated by Django 4.2.30 on 2026-06-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('entry_type', models.CharField(choices=[('feature', 'Feature'), ('fix', 'Fix'), ('deprecation', 'Deprecation'), ('announcement', 'Announcement')], default='feature', max_length=20)),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date', '-id'],
            },
        ),
    ]
